/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopperNotesRouteImport } from './routes/topper-notes'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PastPapersRouteImport } from './routes/past-papers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as HireTopperRouteImport } from './routes/hire-topper'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomRequestsRouteImport } from './routes/custom-requests'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TopperNotesRoute = TopperNotesRouteImport.update({
  id: '/topper-notes',
  path: '/topper-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PastPapersRoute = PastPapersRouteImport.update({
  id: '/past-papers',
  path: '/past-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const HireTopperRoute = HireTopperRouteImport.update({
  id: '/hire-topper',
  path: '/hire-topper',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRequestsRoute = CustomRequestsRouteImport.update({
  id: '/custom-requests',
  path: '/custom-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/custom-requests': typeof CustomRequestsRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/download': typeof DownloadRoute
  '/hire-topper': typeof HireTopperRoute
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/past-papers': typeof PastPapersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/timetable': typeof TimetableRoute
  '/topper-notes': typeof TopperNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/custom-requests': typeof CustomRequestsRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/download': typeof DownloadRoute
  '/hire-topper': typeof HireTopperRoute
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/past-papers': typeof PastPapersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/timetable': typeof TimetableRoute
  '/topper-notes': typeof TopperNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/custom-requests': typeof CustomRequestsRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/download': typeof DownloadRoute
  '/hire-topper': typeof HireTopperRoute
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/past-papers': typeof PastPapersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/timetable': typeof TimetableRoute
  '/topper-notes': typeof TopperNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/custom-requests'
    | '/dashboard'
    | '/discussions'
    | '/download'
    | '/hire-topper'
    | '/homework'
    | '/login'
    | '/notes'
    | '/notifications'
    | '/past-papers'
    | '/profile'
    | '/search'
    | '/signup'
    | '/timetable'
    | '/topper-notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/custom-requests'
    | '/dashboard'
    | '/discussions'
    | '/download'
    | '/hire-topper'
    | '/homework'
    | '/login'
    | '/notes'
    | '/notifications'
    | '/past-papers'
    | '/profile'
    | '/search'
    | '/signup'
    | '/timetable'
    | '/topper-notes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/custom-requests'
    | '/dashboard'
    | '/discussions'
    | '/download'
    | '/hire-topper'
    | '/homework'
    | '/login'
    | '/notes'
    | '/notifications'
    | '/past-papers'
    | '/profile'
    | '/search'
    | '/signup'
    | '/timetable'
    | '/topper-notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  CustomRequestsRoute: typeof CustomRequestsRoute
  DashboardRoute: typeof DashboardRoute
  DiscussionsRoute: typeof DiscussionsRoute
  DownloadRoute: typeof DownloadRoute
  HireTopperRoute: typeof HireTopperRoute
  HomeworkRoute: typeof HomeworkRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  NotificationsRoute: typeof NotificationsRoute
  PastPapersRoute: typeof PastPapersRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TimetableRoute: typeof TimetableRoute
  TopperNotesRoute: typeof TopperNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topper-notes': {
      id: '/topper-notes'
      path: '/topper-notes'
      fullPath: '/topper-notes'
      preLoaderRoute: typeof TopperNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-papers': {
      id: '/past-papers'
      path: '/past-papers'
      fullPath: '/past-papers'
      preLoaderRoute: typeof PastPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-topper': {
      id: '/hire-topper'
      path: '/hire-topper'
      fullPath: '/hire-topper'
      preLoaderRoute: typeof HireTopperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-requests': {
      id: '/custom-requests'
      path: '/custom-requests'
      fullPath: '/custom-requests'
      preLoaderRoute: typeof CustomRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  CustomRequestsRoute: CustomRequestsRoute,
  DashboardRoute: DashboardRoute,
  DiscussionsRoute: DiscussionsRoute,
  DownloadRoute: DownloadRoute,
  HireTopperRoute: HireTopperRoute,
  HomeworkRoute: HomeworkRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  NotificationsRoute: NotificationsRoute,
  PastPapersRoute: PastPapersRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TimetableRoute: TimetableRoute,
  TopperNotesRoute: TopperNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
