name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        working-directory: ./mobile
        run: npm install

      - name: Prebuild Expo App
        working-directory: ./mobile
        run: npx expo prebuild --platform android --clean

      - name: Build APK
        working-directory: ./mobile/android
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: StudyHub-APK
          path: mobile/android/app/build/outputs/apk/release/app-release.apk
